### PR TITLE
raise an error on invalid stubContentMetadata

### LINKED ISSUE #1477: content-metadata-create should raise error on malformed XML from goobi
**Describe the bug**
Goobi accessioning involves:

- sending content files to SDR
- sending a stubContentMetadata.xm file to SDR that lists all the files to be accessioned with some structural metatdata
- telling SDR to start accessioning, which kicks off assemblyWF

For reasons still to be determined, there are cases where the stubContentMetadata.xml sent from Goobi is incomplete. SDR parses this XML anyway and starts accessioning, which results in an incomplete set of files being accessioned.

Example truncated XML:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<content type="Image">
  <resource>
    <label>Page 1</label>
    <file name="gx425hm8798_0001.tif" />
    <file name="gx425hm8798_0001.pdf" />
    <file name="gx425hm8798_0001.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 2</label>
    <file name="gx425hm8798_0002.tif" />
    <file name="gx425hm8798_0002.pdf" />
    <file name="gx425hm8798_0002.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 3</label>
    <file name="gx425hm8798_0003.tif" />
    <file name="gx425hm8798_0003.pdf" />
    <file name="gx425hm8798_0003.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 4</label>
    <file name="gx425hm8798_0004.tif" />
    <file name="gx425hm8798_0004.pdf" />
    <file name="gx425hm8798_0004.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 5</label>
    <file name="gx425hm8798_0005.tif" />
    <file name="gx425hm8798_0005.pdf" />
    <file name="gx425hm8798_0005.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 6</label>
    <file name="gx425hm8798_0006.tif" />
    <file name="gx425hm8798_0006.pdf" />
    <file name="gx425hm8798_0006.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 7</label>
    <file name="gx425hm8798_0007.tif" />
    <file name="gx425hm8798_0007.pdf" />
    <file name="gx425hm8798_0007.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 8</label>
    <file name="gx425hm8798_0008.tif" />
    <file name="gx425hm8798_0008.pdf" />
    <file name="gx425hm8798_0008.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 9</label>
    <file name="gx425hm8798_0009.tif" />
    <file name="gx425hm8798_0009.pdf" />
    <file name="gx425hm8798_0009.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 10</label>
    <file name="gx425hm8798_0010.tif" />
    <file name="gx425hm8798_0010.pdf" />
    <file name="gx425hm8798_0010.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 11</label>
    <file name="gx425hm8798_0011.tif" />
    <file name="gx425hm8798_0011.pdf" />
    <file name="gx425hm8798_0011.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 12</label>
    <file name="gx425hm8798_0012.tif" />
    <file name="gx425hm8798_0012.pdf" />
    <file name="gx425hm8798_0012.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 13</label>
    <file name="gx425hm8798_0013.tif" />
    <file name="gx425hm8798_0013.pdf" />
    <file name="gx425hm8798_0013.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 14</label>
    <file name="gx425hm8798_0014.tif" />
    <file name="gx425hm8798_0014.pdf" />
    <file name="gx425hm8798_0014.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 15</label>
    <file name="gx425hm8798_0015.tif" />
    <file name="gx425hm8798_0015.pdf" />
    <file name="gx425hm8798_0015.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 16</label>
    <file name="gx425hm8798_0016.tif" />
    <file name="gx425hm8798_0016.pdf" />
    <file name="gx425hm8798_0016.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 17</label>
    <file name="gx425hm8798_0017.tif" />
    <file name="gx425hm8798_0017.pdf" />
    <file name="gx425hm8798_0017.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 18</label>
    <file name="gx425hm8798_0018.tif" />
    <file name="gx425hm8798_0018.pdf" />
    <file name="gx425hm8798_0018.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 19</label>
    <file name="gx425hm8798_0019.tif" />
    <file name="gx425hm8798_0019.pdf" />
    <file name="gx425hm8798_0019.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 20</label>
    <file name="gx425hm8798_0020.tif" />
    <file name="gx425hm8798_0020.pdf" />
    <file name="gx425hm8798_0020.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 21</label>
    <file name="gx425hm8798_0021.tif" />
    <file name="gx425hm8798_0021.pdf" />
    <file name="gx425hm8798_0021.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 22</label>
    <file name="gx425hm8798_0022.tif" />
    <file name="gx425hm8798_0022.pdf" />
    <file name="gx425hm8798_0022.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 23</label>
    <file name="gx425hm8798_0023.tif" />
    <file name="gx425hm8798_0023.pdf" />
    <file name="gx425hm8798_0023.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 24</label>
    <file name="gx425hm8798_0024.tif" />
    <file name="gx425hm8798_0024.pdf" />
    <file name="gx425hm8798_0024.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 25</label>
    <file name="gx425hm8798_0025.tif" />
    <file name="gx425hm8798_0025.pdf" />
    <file name="gx425hm8798_0025.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 26</label>
    <file name="gx425hm8798_0026.tif" />
    <file name="gx425hm8798_0026.pdf" />
    <file name="gx425hm8798_0026.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 27</label>
    <file name="gx425hm8798_0027.tif" />
    <file name="gx425hm8798_0027.pdf" />
    <file name="gx425hm8798_0027.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 28</label>
    <file name="gx425hm8798_0028.tif" />
    <file name="gx425hm8798_0028.pdf" />
    <file name="gx425hm8798_0028.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 29</label>
    <file name="gx425hm8798_0029.tif" />
    <file name="gx425hm8798_0029.pdf" />
    <file name="gx425hm8798_0029.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 30</label>
    <file name="gx425hm8798_0030.tif" />
    <file name="gx425hm8798_0030.pdf" />
    <file name="gx425hm8798_0030.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 31</label>
    <file name="gx425hm8798_0031.tif" />
    <file name="gx425hm8798_0031.pdf" />
    <file name="gx425hm8798_0031.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 32</label>
    <file name="gx425hm8798_0032.tif" />
    <file name="gx425hm8798_0032.pdf" />
    <file name="gx425hm8798_0032.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <label>Page 33</label>
    <file name="gx425hm8798_0033.tif" />
    <file name="gx425hm8798_0033.pdf" />
    <file name="gx425hm8798_0033.xml" role="transcription" publish="yes" preserve="yes" shelve="yes" />
  </resource>
  <resource>
    <
```

**User Impact**
Users think they've accessioned all the files in an item but some files are missing. This might not be discovered until after the missing files are deleted from the Goobi system.

**To Reproduce**

We're not sure yet how to reproduce for testing, but both these items have this issue:

- https://argo.stanford.edu/view/druid:gx425hm8798
- https://argo.stanford.edu/view/druid:cc703by3112

In both cases, the same number of files/resources were included in the SDR item, suggesting the cutoff may be number of lines or even number of characters.

**Expected behavior**
Accessioning should not start without a complete stubContentMetadata.xml

**Additional context**
@peetucket already created a PR for this issue #1476

### PR DESCRIPTION
**Pull request by peetucket**
## Why was this change made? 🤔

Fixes #1477 

Currently partial and malformed stubContentMetadata.xml that is exported from Goobi is happily processed but results in incomplete objects.  This change will now cause an error to be raised and thus put the content-metadata-create step to be placed in error with an appropriate message if this happens.

See https://stanfordlib.slack.com/archives/C0EAZ09QF/p1743445147202589 for the reasoning behind this change.

Note: it also reverts #1475 since we don't need that anymore (this will put the step in error, leaving the file in the workspace for further debugging)

## How was this change tested? 🤨

New specs

### CODE REVIEW

File: lib/robots/dor_repo/assembly/content_metadata_create.rb [hunk 1]
```diff
@@ -19,8 +19,8 @@ def perform_work
           updated = assembly_item.cocina_model.new(structural: assembly_item.convert_stub_content_metadata)
           assembly_item.object_client.update(params: updated)
 
-          # Backup the stubContentMetadata.xml
-          FileUtils.mv(assembly_item.stub_cm_file_name, File.join('/dor/stopped', "#{druid}-#{Settings.assembly.stub_cm_file_name}"))
+          # Remove the stubContentMetadata.xml
+          FileUtils.rm(assembly_item.stub_cm_file_name)
```
Comment (peetucket) [inline lib/robots/dor_repo/assembly/content_metadata_create.rb:23]: this reverts #1475

File: spec/lib/dor/assembly/stub_content_metadata_parser_spec.rb [hunk 2]
```diff
@@ -210,5 +210,13 @@
...
       end
     end
+
+    context 'with malformed XML' do
+      let(:druid) { 'druid:bb111bb7777' }
+
+      it 'raises an error' do
+        expect { item.convert_stub_content_metadata }.to raise_error(RuntimeError, /Invalid stubContentMetadata.xml/)
+      end
+    end
```
Comment (peetucket) [inline spec/lib/dor/assembly/stub_content_metadata_parser_spec.rb:220]: there is a new malformed xml file below used for this test

File: spec/robots/dor_repo/assembly/content_metadata_create_spec.rb [hunk 3]
```diff
@@ -9,9 +9,6 @@
   let(:robot) { described_class.new }
   let(:type) { 'item' }
   let(:cocina_model) { build(:dro, id: "druid:#{druid}") }
-  let(:ng_xml) do
-    Nokogiri::XML('<contentMetadata type="image"></contentMetadata>')
-  end
```
Comment (peetucket) [inline spec/robots/dor_repo/assembly/content_metadata_create_spec.rb:14]: cleanup - unused by the spec

**Review by justinlittman — APPROVED** [review]
