### PR TITLE
FIX BUG:  desc metadata required fields check

### LINKED ISSUE #393: registered object with catkey and no label gets "no title" err from descMetadata step
Here's the error:

image

But descMetadata exists:

image

And has title:

image

So the fetch from Symphony worked ... but the check seems to have run first

related to #386

### PR DESCRIPTION
**Pull request by ndushay**
Fixes #393 
related to #386, and may fix that as well

We have been getting this error but inappropriately -- the descMetadata is there and it has a title:

image

I was able to reproduce the error in stage consistently by registering an object with a catkey and no label, and then adding the accessioningWF.

This PR fixes the problem by reloading the Dor object before checking for required fields in a possibly newly updated datastream.

I deployed the fix to stage and empirically established that the fix works.

### CODE REVIEW

**Comment by ndushay** [comment]
@andrewjbtw w00t!   This took me entirely too long, but I do believe this was the problem.

File: lib/robots/dor_repo/accession/descriptive_metadata.rb [hunk 1]
```diff
@@ -21,6 +21,7 @@ def perform(druid)
             Dor::Services::Client.object(druid).refresh_metadata
           end
 
+          obj = Dor.find(druid) # reload object to get latest content
```
Comment (mjgiarlo) [inline lib/robots/dor_repo/accession/descriptive_metadata.rb]: `obj.reload` should work as well but it's NBD!
